### ISSUE TITLE
Placeable firefly jars

### ISSUE THREAD

**Issue by Sos339** [MysticMods/Firefly#2]
Similar to twilight forest firefly jars but maybe a different model/texture
Jars would be varied colors based on the firefly and would emit light

http://www.benimatic.com/tfwiki/images/9/93/Twilight_Forest_Firefly_Jar.png

**Comment by VulpTheKangaFox** [comment]
Already a planned feature, but might not come along immediately.

**Comment by Sos339** [comment]
closing issue because implemented
